# Generated by Django 2.2.14 on 2020-07-30 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='body',
        ),
    ]
