# Generated by Django 2.2.14 on 2020-07-16 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_books'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
