# Generated by Django 3.1 on 2020-08-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_book_blog_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(default='Nothing_Yet', upload_to='book_images/'),
        ),
    ]
