# Generated by Django 3.1 on 2020-08-11 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_book_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledge',
            name='slug',
        ),
    ]
