# Generated by Django 3.1 on 2020-08-11 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_postbase_display'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover_description',
        ),
        migrations.RemoveField(
            model_name='book',
            name='image_name',
        ),
        migrations.RemoveField(
            model_name='postbase',
            name='tags',
        ),
    ]
