# Generated by Django 2.2.14 on 2020-07-27 16:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200721_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledge',
            name='tags',
        ),
        migrations.AddField(
            model_name='knowledge',
            name='tags',
            field=models.TextField(default='Placeholder'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 27, 16, 35, 33, 256522, tzinfo=utc)),
        ),
    ]
