# Generated by Django 3.1 on 2020-08-21 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapey', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SPost',
            new_name='Post',
        ),
    ]
