# Generated by Django 2.2.14 on 2020-08-02 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_book_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='blog_display',
            field=models.BooleanField(default=False),
        ),
    ]
